import { Fredoka } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const claritycity = Fredoka({ 
  weight: ['400', '600'],
  display:'swap',
  subsets: ["latin"],
});

export const metadata = {
  title: "Travel Next App",
  description: "Generated by create next app",
}



export default function RootLayout({ children }) {
  return (
    <html  lang="en"  className={`${claritycity.className}  `}>
      <body className="w-screen h-screen bg-black text-white">
        <Nav />
        {children}
      </body>
    </html>
  );
}
