 
import "./globals.css";
import {Tangerine} from "next/font/google"; 
 
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tangerine_Font = Tangerine({
  subsets: ["latin"],
  weight: ["400", "700"], //Available weights: 400, 700
  display:"swap"
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${tangerine_Font.className} min-h-full flex flex-col`}>
        {children}
        </body>
    </html>
  );
}
