import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, team }) {
  return (
    <html  lang="en"  className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      {/* <body className="w-screeen h-screen flex ">
        <div className="w-[20%] bg-green-200 text-center">{children}</div>
        <div className="w-[30%] bg-blue-200 text-center">{team}</div>
        <div className="w-[50%] bg-pink-200 text-center">{team}</div>
      </body> */}
      <body className="">
        <div className="w-screen h-screen bg-green-200 text-center">{children}</div> 
      </body>
    </html>
  );
}
